exclude: ^(3rd_party/)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      args: ["--unsafe"]
    - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.1
  hooks:
  - id: clang-format
    types_or: [c++, c]
